;; Licensed to the .NET Foundation under one or more agreements.
;; The .NET Foundation licenses this file to you under the MIT license.

;; OS provided macros
#include <ksarm.h>
;; generated by the build from AsmOffsets.cpp
#include "AsmOffsets.inc"
#include <..\..\..\vm\arm\asmconstants.h>

#define OFFSETOF__ee_alloc_context__alloc_ptr (OFFSETOF__ee_alloc_context__m_rgbAllocContextBuffer + OFFSETOF__gc_alloc_context__alloc_ptr)
#define OFFSETOF__ee_alloc_context            OFFSETOF__Thread__m_eeAllocContext

#define GC_ALLOC_FINALIZE           1
#define GC_ALLOC_ALIGN8_BIAS        4
#define GC_ALLOC_ALIGN8             8

#define G_FREE_OBJECT_METHOD_TABLE  g_pFreeObjectEEType

;
; CONSTANTS -- INTEGER
;

#define TSF_Attached                    0x01
#define TSF_SuppressGcStress            0x08
#define TSF_DoNotTriggerGc              0x10

#define PTFF_SAVE_ALL_PRESERVED 0x0000007F
#define PTFF_SAVE_R9 0x00000020
#define PTFF_SAVE_SP 0x00000100
#define PTFF_SAVE_R0 0x00000200
#define PTFF_THREAD_HIJACK 0x00004000

#define DEFAULT_FRAME_SAVE_FLAGS (PTFF_SAVE_ALL_PRESERVED + PTFF_SAVE_SP)

; These must match the TrapThreadsFlags enum
#define TrapThreadsFlags_None            0
#define TrapThreadsFlags_TrapThreads     1

#define INVALIDGCVALUE 0xCCCCCCCD

; Platform-specific macro definitions
#if defined(__APPLE__)
#define C_FUNC(name) _##name
#define EXTERNAL_C_FUNC(name) C_FUNC(name)
#define LOCAL_LABEL(name) L##name
#elif defined(_WIN32) || defined(_WIN64)
#define C_FUNC(name) name
#define EXTERNAL_C_FUNC(name) name
#define LOCAL_LABEL(name) name
#else
#define C_FUNC(name) name
#define EXTERNAL_C_FUNC(name) C_FUNC(name)@plt
#define LOCAL_LABEL(name) .L##name
#endif

#if defined(__APPLE__)
#define C_PLTFUNC(name) _##name
#elif defined(_WIN32) || defined(_WIN64)
#define C_PLTFUNC(name) name
#else
#define C_PLTFUNC(name) name@PLT
#endif

    MACRO
    END_PROLOGUE
    MEND

    MACRO
      SETALIAS   $name, $symbol
        GBLS    $name
$name   SETS    "|$symbol|"
    MEND
	
	SETALIAS G_FREE_OBJECT_EETYPE, ?g_pFreeObjectEEType@@3PAVMethodTable@@A
	EXTERN $G_FREE_OBJECT_EETYPE

; GC minimal sized object.  We use this to switch between 4 and 8 byte alignment in the GC heap (see AllocFast. asm).
#define ASM_MIN_OBJECT_SIZE 12


;;
;; IMPORTS
;;
	EXTERN GetThreadEEAllocContext
    EXTERN RhpGcAlloc
    EXTERN RhExceptionHandling_FailedAllocation
    EXTERN RhDebugBreak
    EXTERN RhpWaitForGC2
    EXTERN RhThrowHwEx
    EXTERN RhThrowEx
    EXTERN RhRethrow
    EXTERN RhpGetThread

    EXTERN RhpTrapThreads
    EXTERN g_lowest_address
    EXTERN g_highest_address
    EXTERN g_ephemeral_low
    EXTERN g_ephemeral_high
    EXTERN g_card_table

#ifdef FEATURE_MANUALLY_MANAGED_CARD_BUNDLES
    EXTERN g_card_bundle_table
#endif

#ifdef FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP
    EXTERN g_write_watch_table
#endif

    EXTERN g_cpuFeatures
	
	;;
;; MACROS
;;

	MACRO
	GLOBAL_LABEL $FuncName
	
	ALTERNATE_ENTRY $FuncName
	
	MEND

 MACRO
    PATCH_LABEL $FuncName
$FuncName
    EXPORT $FuncName

    MEND

    MACRO
    PREPARE_EXTERNAL_VAR $Name, $HelperReg
		EXTERN $Name
        ldr $HelperReg, =C_FUNC($Name)
    MEND

    MACRO
    PREPARE_EXTERNAL_VAR_INDIRECT $Name, $HelperReg
		EXTERN $Name
        ldr $HelperReg, =C_FUNC($Name)
        ldr $HelperReg, [$HelperReg]
    MEND

    MACRO
    push_nonvol_reg $Register
        push $Register
    MEND

    MACRO
    pop_nonvol_reg $Register
        pop $Register
    MEND

    MACRO
    vpush_nonvol_reg $Register
        vpush $Register
    MEND

    MACRO
    vpop_nonvol_reg $Register
        vpop $Register
    MEND

    MACRO
    alloc_stack $Size
        sub sp, sp, ($Size)
    MEND

    MACRO
    free_stack $Size
        add sp, sp, ($Size)
    MEND

    MACRO
    POP_CALLEE_SAVED_REGISTERS
        pop_nonvol_reg "{r4-r11, lr}"
    MEND

    MACRO
    PUSH_CALLEE_SAVED_REGISTERS
        push_nonvol_reg "{r4-r11, lr}"
    MEND

    MACRO
    push_register $Reg
        push $Reg
    MEND

    MACRO
    push_argument_register $Reg
        push_register $Reg
    MEND

    MACRO
    PUSH_ARGUMENT_REGISTERS
        push {r0-r3}
    MEND

    MACRO
    pop_register $Reg
        pop $Reg
    MEND

    MACRO
    pop_argument_register $Reg
        pop_register $Reg
    MEND

    MACRO
    POP_ARGUMENT_REGISTERS
        pop {r0-r3}
    MEND

;-----------------------------------------------------------------------------
; Macro used to check (in debug builds only) whether the stack is 64-bit aligned (a requirement before calling
; out into C++/OS code). Invoke this directly after your prolog (if the stack frame size is fixed) or directly
; before a call (if you have a frame pointer and a dynamic stack). A breakpoint will be invoked if the stack
; is misaligned.
;
    MACRO
    CHECK_STACK_ALIGNMENT

#ifdef _DEBUG
        push {r0}
        add r0, sp, #4
        tst r0, #7
        pop {r0}
        beq %FT0
        EMIT_BREAKPOINT
0
#endif
    MEND

; Loads a 32bit constant into destination register
    MACRO
    MOV32 $DestReg, $Constant
        movw $DestReg, #(($Constant) :AND:  0xFFFF)
        movt $DestReg, #(($Constant) :SHR: 16)
    MEND
	
    MACRO
    PROLOG_STACK_SAVE_OFFSET $Register, $Offset
        add $Register, sp, $Offset
    MEND	

;
; Macro used from unmanaged helpers called from managed code where the helper does not transition immediately
; into pre-emptive mode but may cause a GC and thus requires the stack is crawlable. This is typically the
; case for helpers that meddle in GC state (e.g. allocation helpers) where the code must remain in
; cooperative mode since it handles object references and internal GC state directly but a garbage collection
; may be inevitable.  In these cases we need to be able to transition to pre-meptive mode deep within the
; unmanaged code but still be able to initialize the stack iterator at the first stack frame which may hold
; interesting GC references.  In all our helper cases this corresponds to the most recent managed frame (e.g.
; the helper's caller).
;
; This macro builds a frame describing the current state of managed code. 
;
; INVARIANTS
; - The macro assumes it defines the method prolog, it should typically be the first code in a method and
;   certainly appear before any attempt to alter the stack pointer.
; - This macro uses trashReg (after its initial value has been saved in the frame) and upon exit trashReg
;   will contain the address of transition frame.
;
    MACRO
    PUSH_COOP_PINVOKE_FRAME $target
	
        PROLOG_STACK_ALLOC 4          // Save space for caller's SP
        PROLOG_PUSH {r4-r10}          // Save preserved registers
        PROLOG_STACK_ALLOC 8          // Save space for flags and Thread*
        PROLOG_PUSH {r11,lr}          // Save caller's frame pointer and PC
		
        // Compute SP value at entry to this method and save it in the last slot of the frame (slot #12).
        add         $target, sp, #(12 * 4)
        str         $target, [sp, #(11 * 4)]

        // Record the bitmask of saved registers in the frame (slot #3).
        mov         $target, #DEFAULT_FRAME_SAVE_FLAGS
        str         $target, [sp, #(3 * 4)]

        mov         $target, sp
    MEND

    MACRO
    POP_COOP_PINVOKE_FRAME
        EPILOG_POP  {r11,lr}          // Restore caller's frame pointer and PC (return address)
        EPILOG_STACK_FREE 8           // Discard flags and Thread*
        EPILOG_POP  {r4-r10}          // Restore preserved registers
        EPILOG_STACK_FREE 4           // Discard caller's SP
    MEND

__tls_array                         equ 0x2C    ;; offsetof(TEB, ThreadLocalStoragePointer)

        GBLS __SECTIONREL_tls_CurrentThread
__SECTIONREL_tls_CurrentThread SETS "SECTIONREL_tls_CurrentThread"

    ; MACRO
    ;     INLINE_GETTHREAD $destReg, $trashReg
    ;     EXTERN _tls_index
	;
    ;     ldr         $destReg, =_tls_index
    ;     ldr         $destReg, [$destReg]
    ;     mrc         p15, 0, $trashReg, c13, c0, 2
    ;     ldr         $trashReg, [$trashReg, #__tls_array]
    ;     ldr         $destReg, [$trashReg, $destReg, lsl #2]
    ;     ldr.w       $trashReg, $__SECTIONREL_tls_CurrentThread
    ;     add         $destReg, $trashReg
    ; MEND
	
	MACRO
		INLINE_GETTHREAD $destReg, $trashReg
		bl RhpGetThread
	MEND
	
        ;; INLINE_GETTHREAD_CONSTANT_POOL macro has to be used after the last function in the .asm file that used
        ;; INLINE_GETTHREAD. Optionally, it can be also used after any function that used INLINE_GETTHREAD
        ;; to improve density, or to reduce distance betweeen the constant pool and its use.
    MACRO
        INLINE_GETTHREAD_CONSTANT_POOL
        EXTERN tls_CurrentThread

$__SECTIONREL_tls_CurrentThread
        DCD tls_CurrentThread
        RELOC 15 ;; SECREL

__SECTIONREL_tls_CurrentThread SETS "$__SECTIONREL_tls_CurrentThread":CC:"_"

    MEND

	MACRO
	INLINE_GET_ALLOC_CONTEXT_BASE
		INLINE_GETTHREAD
	MEND

    MACRO
    INLINE_THREAD_UNHIJACK $threadReg, $trashReg1, $trashReg2
        ;
        ; Thread::Unhijack()
        ;
        ldr         $trashReg1, [$threadReg, #OFFSETOF__Thread__m_pvHijackedReturnAddress]
        cbz         $trashReg1, %FT1

        ldr         $trashReg2, [$threadReg, #OFFSETOF__Thread__m_ppvHijackedReturnAddressLocation]
        str         $trashReg1, [$trashReg2]
        mov         $trashReg1, #0
        str         $trashReg1, [$threadReg, #OFFSETOF__Thread__m_ppvHijackedReturnAddressLocation]
        str         $trashReg1, [$threadReg, #OFFSETOF__Thread__m_pvHijackedReturnAddress]

1
    MEND